#define TITLESCREEN 0
#define INSTRUCTIONS_INGAME 1 
#define INGAME 2
#define RESULTS 3

#define WIDTH_LIMIT_MIN 1
#define WIDTH_LIMIT_MAX 284
#define HEIGHT_LIMIT_MIN 150
#define HEIGHT_LIMIT_MAX 432
